### PR TITLE
[Feature] Convert all images in the project to webp

### PR DESCRIPTION
**Pull request by gtrabanco**
Script to convert all images to webp:

```
bun webp
```

You can give `rm` argument to delete old images (png, jpeg, jpg). It does not compress any image, maybe that can be a good idea but that is up to you 😅

I have checked that works but decide to convert all images or not is also up to you because the change is huge in size.

## TODO

- [x] Generate thumbnails for the gallery. 365px minimum side images.
- [ ] Download all gallery images script
- ~~[ ] Try to remove background on thumbnails in the gallery to scale only the person. 🚬🚬 I will try 🚬🚬.~~ I will try this by my own and I will do another PR if it seems cool :)

### CODE REVIEW

**Comment by gtrabanco** [comment]
- ~~Now uses only webp files. You will need to run `bun gallery` to generate thumnails and convert jpeg files to webp. I won't do it to avoid a big PR due big file changes.~~
- ~~You can generate new thumbnails and remove old jpeg on the fly by using `bun gallery rm`.~~

This PR will have conflicts with other PRs that modify <Galeria> Astro component like #46

**Comment by gtrabanco** [comment]
If you consider fine, change quality param in all image conversions to `80` will reduce the size of files while keeping good quality.

**Comment by midudev** [comment]
Pinta bien la idea!

**Comment by gtrabanco** [comment]
I have deleted `gallery` script.

I have downloaded all images and adapted `<Galeria>` and `<Archivo>` components. Maybe add some nice scrolling would be a nice idea.

If you want to download all images again you only should execute: `bun dl` it will download all images for honors (palmarés) and all gallery in webp. It takes a little bit even with Bun and good connection due file conversion to webp with sharp.


Ready to merge

## Important

The gallery file 73 only has thumbnail (in official page too) and there is a file 74 that has not thumbnail in the official webpage.

**Pull request merged**
